name: DungeonMe
main: com.worldcretornica.dungeonme.DungeonMe
version: ${project.version}
author: ZachBora
load: startup
description: >
             Infinite Dungeon Generator
commands:
    dungeonme:
      description: List DungeonMe commands
      usage: /dungeonme